name: Build status

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.7.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Generate coverage report
        run: |
          pytest --cov=./ --cov-report=xml
        env:
          FLASK_ENV: "testing"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
      - name: Test with pytest
        run: |
          pytest
        env:
          FLASK_ENV: "testing"
      - name: Update release draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release_config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE }}